# **Bibliotecas**

In [46]:
#Bibliotecas 
import pandas as pd
import numpy as np #Matrizes e Arreys
import matplotlib.pyplot as plt #Analise visual
import seaborn as sns
import sklearn.model_selection as ms 
import math

from sklearn.compose import make_column_transformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

In [13]:
train = pd.read_csv('drive/MyDrive/dados/train.csv')
Y = pd.read_csv('drive/MyDrive/dados/test.csv')
train

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,9276_01,Europa,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther,False
8689,9278_01,Earth,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley,False
8690,9279_01,Earth,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon,True
8691,9280_01,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,False
8692,9280_02,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,True

Analisando a mediano (dados numericos)

In [18]:
train.describe()

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
count,8514.000000,8512.000000,8510.000000,8485.000000,8510.000000,8505.000000
mean,28.827930,224.687617,458.077203,173.729169,311.138778,304.854791
std,14.489021,666.717663,1611.489240,604.696458,1136.705535,1145.717189
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,19.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,38.000000,47.000000,76.000000,27.000000,59.000000,46.000000
max,79.000000,14327.000000,29813.000000,23492.000000,22408.000000,24133.000000

In [15]:
#dados object
train.describe(include=['object'])

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,VIP,Name
count,8693,8492,8476,8494,8511,8490,8493
unique,8693,3,2,6560,3,2,8473
top,0001_01,Earth,False,G/734/S,TRAPPIST-1e,False,Gollux Reedall
freq,1,4602,5439,8,5915,8291,2

In [16]:
train['Transported'].describe()

count     8693
unique       2
top       True
freq      4378
Name: Transported, dtype: object

In [17]:
train.loc[train['Transported'] ]

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True
5,0005_01,Earth,False,F/0/P,PSO J318.5-22,44.0,False,0.0,483.0,0.0,291.0,0.0,Sandie Hinetthews,True
6,0006_01,Earth,False,F/2/S,TRAPPIST-1e,26.0,False,42.0,1539.0,3.0,0.0,0.0,Billex Jacostaffey,True
7,0006_02,Earth,True,G/0/S,TRAPPIST-1e,28.0,False,0.0,0.0,0.0,0.0,NaN,Candra Jacostaffey,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8684,9274_01,NaN,True,G/1508/P,TRAPPIST-1e,23.0,False,0.0,0.0,0.0,0.0,0.0,Chelsa Bullisey,True
8685,9275_01,Europa,False,A/97/P,TRAPPIST-1e,0.0,False,0.0,0.0,0.0,0.0,0.0,Polaton Conable,True
8687,9275_03,Europa,NaN,A/97/P,TRAPPIST-1e,30.0,False,0.0,3208.0,0.0,2.0,330.0,Atlasym Conable,True
8690,9279_01,Earth,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon,True
8692,9280_02,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,True

In [28]:
train.columns

Index(['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age',
       'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck',
       'Name', 'Transported'],
      dtype='object')

In [21]:
#RoomService
train['RoomService'].fillna('RoomService')

0         0.0
1       109.0
2        43.0
3         0.0
4       303.0
        ...
8688      0.0
8689      0.0
8690      0.0
8691      0.0
8692    126.0
Name: RoomService, Length: 8693, dtype: object

In [22]:
train['RoomService'].median()

0.0

In [23]:
train['Age'].fillna('Age')

0       39.0
1       24.0
2       58.0
3       33.0
4       16.0
        ...
8688    41.0
8689    18.0
8690    26.0
8691    32.0
8692    44.0
Name: Age, Length: 8693, dtype: object

In [24]:
train['Age'].median()

27.0

In [25]:
train['FoodCourt'].fillna('FoodCourt')

0          0.0
1          9.0
2       3576.0
3       1283.0
4         70.0
         ...
8688    6819.0
8689       0.0
8690       0.0
8691    1049.0
8692    4688.0
Name: FoodCourt, Length: 8693, dtype: object

In [26]:
train['FoodCourt'].median()

0.0

In [31]:
train['ShoppingMall'].fillna('ShoppingMall')

0          0.0
1         25.0
2          0.0
3        371.0
4        151.0
         ...
8688       0.0
8689       0.0
8690    1872.0
8691       0.0
8692       0.0
Name: ShoppingMall, Length: 8693, dtype: object

In [30]:
train['ShoppingMall'].median()

0.0

In [32]:
train['Spa'].fillna('Spa')

0          0.0
1        549.0
2       6715.0
3       3329.0
4        565.0
         ...
8688    1643.0
8689       0.0
8690       1.0
8691     353.0
8692       0.0
Name: Spa, Length: 8693, dtype: object

In [33]:
train['Spa'].median()

0.0

In [34]:
train['VRDeck'].fillna('VRDeck')

0          0.0
1         44.0
2         49.0
3        193.0
4          2.0
         ...
8688      74.0
8689       0.0
8690       0.0
8691    3235.0
8692      12.0
Name: VRDeck, Length: 8693, dtype: object

In [35]:
train['VRDeck'].median()

0.0

In [55]:
#Divisao dos dados
from sklearn.model_selection import train_test_split

X = train.drop(['Transported'], axis = "columns")
y = train.Transported

column_names_train = train.drop(['Transported'], axis = "columns").columns
column_name_target = train[['Transported']].columns

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 13)

In [43]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8492 non-null   object
 2   CryoSleep     8476 non-null   object
 3   Cabin         8494 non-null   object
 4   Destination   8511 non-null   object
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object
 13  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB

In [72]:
non_numeric_columns = ['HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'VIP']
train[non_numeric_columns].agg(['unique'])

,HomePlanet,CryoSleep,Cabin,Destination,VIP
unique,"[Europa, Earth, Mars, nan]","[False, True, nan]","[B/0/P, F/0/S, A/0/S, F/1/S, F/0/P, F/2/S, G/0...","[TRAPPIST-1e, PSO J318.5-22, 55 Cancri e, nan]","[False, True, nan]"

In [73]:
#Usando o One Hot Encoder das colunas string
encoder_transformer = make_column_transformer(
    (OneHotEncoder(), ['HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'VIP'])
)

encoder_transformer.fit(X_train)

encoder_transformer.transform(X_train)

<6085x4885 sparse matrix of type '<class 'numpy.float64'>'
	with 30425 stored elements in Compressed Sparse Row format>

In [75]:
#encoder de todas as variaveis não numericas
from sklearn.compose import make_column_selector

encoder_transformer = make_column_transformer(
    (OneHotEncoder(), make_column_selector(dtype_exclude = np.number)),
    remainder = 'passthrough'
)

encoder_transformer.fit(X_train)

X_train_encoded = encoder_transformer.transform(X_train)
X_train_encoded

<6085x16909 sparse matrix of type '<class 'numpy.float64'>'
	with 59782 stored elements in Compressed Sparse Row format>

In [76]:
#utilização de média incondicional para preencher os valores ausentes.
from sklearn.compose import make_column_selector

encoder_imputer_transformer = make_column_transformer(
    (OneHotEncoder(handle_unknown = 'ignore'), make_column_selector(dtype_exclude = np.number)),
    (SimpleImputer(missing_values=np.nan, strategy = 'mean'), make_column_selector(dtype_include = np.number)),
    remainder = 'passthrough'
)

encoder_imputer_transformer.fit(X_train)

X_train_encoded_imputed = encoder_imputer_transformer.fit_transform(X_train)
X_train_encoded_imputed

<6085x16909 sparse matrix of type '<class 'numpy.float64'>'
	with 59782 stored elements in Compressed Sparse Row format>

In [77]:
#pre_processamento de test
X_test_encoded_imputed = encoder_imputer_transformer.transform(X_test)
X_test_encoded_imputed

<2608x16909 sparse matrix of type '<class 'numpy.float64'>'
	with 18695 stored elements in Compressed Sparse Row format>

In [80]:
from sklearn.neighbors import KNeighborsClassifier

def train_knn_classifier(X_train, y_train, k):
  knn = KNeighborsClassifier(n_neighbors = k)
  knn.fit(X_train, y_train)
  return knn

trained_knn = train_knn_classifier(X_train_encoded_imputed, y_train, 3)
  
y_pred = trained_knn.predict(X_test_encoded_imputed)
y_pred

array([ True,  True,  True, ..., False, False,  True])

In [81]:
#primeira tentativa de testar o desempenho
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_true = y_test, 
                          y_pred = y_pred)

accuracy

0.7519171779141104

In [86]:
#Segunda tentativa
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

encoder_imputer_scaled_transformer = make_column_transformer(
    (make_pipeline(
        (SimpleImputer(strategy = 'mean')),
        (StandardScaler())
    ) , make_column_selector(dtype_include = np.number)),
    (make_pipeline(
        SimpleImputer(strategy = 'most_frequent'),
        OneHotEncoder(handle_unknown = 'ignore'),
    ), make_column_selector(dtype_exclude = np.number)),
    remainder = 'passthrough'
)


encoder_imputer_scaled_transformer.fit(X_train)

X_train_encoded_imputed_scaled = encoder_imputer_scaled_transformer.transform(X_train)
X_test_encoded_imputed_scaled = encoder_imputer_scaled_transformer.transform(X_test)

In [87]:
trained_knn2 = train_knn_classifier(X_train_encoded_imputed_scaled, y_train, 3)

y_pred2 = trained_knn2.predict(X_test_encoded_imputed_scaled)

accuracy = accuracy_score(y_true = y_test, 
                          y_pred = y_pred2)

accuracy

0.7576687116564417